### ISSUE TITLE
R package actuar on GDUserv

### ISSUE THREAD

**Issue by mevers** [mevers/NCI_ChIP-seq#4]
GDUserv runs R version
```
R version 3.1.0 (2014-04-10) -- "Spring Dance"
Copyright (C) 2014 The R Foundation for Statistical Computing
Platform: x86_64-unknown-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
http://www.gnu.org/licenses/.
```
Unfortunately, R version 3.1.0 does not support the most recent version 2.1.0 of R package `actuar`, which is required for `scripts/simulate_reads.R`.
This will break the workflow.

**Workaround**: It seems that [`actuar` version 1.1.10](https://cran.r-project.org/src/contrib/Archive/actuar/actuar_1.1-10.tar.gz) installs on R 3.1.0. Install manually and locally using
```
install.packages("actuar_1.1-10.tar.gz");
```

**Comment by skurscheid** [comment]
see above for fix
